# k8s/01-config/kfood-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kfood-api-keys
  namespace: default
type: Opaque
data:
  # Base64로 인코딩된 Gemini API 키로 대체할 것 (Backend API Pod가 참조)
  GEMINI_API_KEY: AEl6YVN5RXhhbXBsZUtleQ== 
  
  # 번역 서비스 API 키 (Translate Service Pod가 참조)
  # GOOGLE_TRANSLATE_API_KEY: VHJhbnNsYXRlU2VydmljZUtleQ==